/**
 * Maintainer-only import/inspection of one first-party Microsandbox image
 * candidate. Identity inputs are an exact repository receipt and the current
 * server-owned distribution matrix. The orchestration re-parses and re-binds
 * that receipt to the matrix before any Docker or Microsandbox effect.
 *
 * Three immutable provenance fields stay separately recorded:
 * 1. OCI index digest from Buildx
 * 2. linux/arm64 OCI platform-manifest digest pulled from Docker
 * 3. Microsandbox manifest digest observed after docker save + Image.load
 *
 * Their hash text can coincide; neither a comparison nor a record collapses
 * the three provenance fields into one identity.
 *
 * This path never calls acquireFirstPartyMicrosandboxImage (that imports under
 * the active catalogue pin). Microsandbox SDK 0.6.8 has no tag/relabel API:
 * staging is Image.load(archive, { tag: staging }), then exact Image.remove of
 * that staging reference, then a second Image.load of the same archive with
 * the canonical Microsandbox cache reference
 * docker.io/casys/first-party-candidate-<physicalImageId>@sha256:<observed-msb-digest>
 * derived by pinnedOciImageReference. The factual import record still stores
 * the short casys/first-party-candidate-<physicalImageId>@sha256:<observed-msb-digest>
 * as candidateReference. That second load is a re-import that applies the
 * cache reference, not an in-place retag.
 */

import { samePinnedRepositoryDigest } from "../shared/docker-pinned-repository-digest.ts";
import { pinnedOciImageReference } from "../../domain/compile/isolation/local-isolation-runtime.ts";
import type {
  MicrosandboxImageImportHandle,
  MicrosandboxImageInspection,
} from "../shared/execution/microsandbox-ephemeral-execution-backend.ts";
import {
  deterministicJson,
  sha256Hex,
} from "../../domain/kernel/deterministic-json.ts";
import {
  assertAllowedFirstPartyBootstrapTempPath,
  type DockerSourceInspection,
  type FirstPartyMicrosandboxTemporaryArchive,
  parseDockerSourceInspection,
} from "./first-party-microsandbox-image-acquisition.ts";
import {
  type FirstPartyMicrosandboxImageCandidateReceipt,
  readBoundFirstPartyMicrosandboxImageCandidateReceipt,
} from "./first-party-microsandbox-image-candidate-receipt.ts";
import type { FirstPartyMicrosandboxImageDistributionMatrix } from "./first-party-microsandbox-image-distribution-matrix.ts";
import {
  buildFirstPartyMicrosandboxImageCandidateImportRecord,
  type FirstPartyMicrosandboxImageCandidateImportRecord,
  firstPartyMicrosandboxImageCandidateName,
  firstPartyMicrosandboxImageCandidateReference,
} from "./first-party-microsandbox-image-candidate-import-record.ts";

export const FIRST_PARTY_MICROSANDBOX_IMAGE_CANDIDATE_IMPORT_PLAN_SCHEMA =
  "first-party-microsandbox-image-candidate-import-plan/2.0" as const;

const SHA256 = /^sha256:[0-9a-f]{64}$/u;
const STAGING_REPOSITORY_PREFIX = "casys/first-party-candidate-staging-" as const;
const STAGING_TOKEN = /^[a-z0-9](?:[a-z0-9-]{0,63})?$/u;
const DOCKER_TAG = /^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$/u;
const MAXIMUM_STAGING_LOCATOR_PREFIX_LENGTH = 63;

export interface FirstPartyMicrosandboxImageCandidateImportPorts {
  readonly hostArchitecture: string;
  /**
   * Invocation-owned nonce. It is generated by the server/composition at run
   * time, never supplied by a caller and never persisted in the factual
   * candidate record.
   */
  createStagingToken(): string;
  inspectOciIndex(reference: string): Promise<string>;
  pullByDigest(reference: string): Promise<void>;
  inspectDockerImage(reference: string): Promise<unknown | undefined>;
  saveDockerImage(reference: string, archivePath: string): Promise<void>;
  loadImageFromArchive(
    archivePath: string,
    tag: string,
  ): Promise<readonly MicrosandboxImageImportHandle[]>;
  inspectCachedImage(reference: string): Promise<MicrosandboxImageInspection>;
  isImageNotFound(error: unknown): boolean;
  /**
   * Exact Microsandbox cached-image removal. No force, prune, or volume.
   * Callers of this port from the candidate-import flow may pass only the
   * exact staging reference or the exact canonical cache reference derived
   * for this physical candidate digest.
   */
  removeExactCachedImage(reference: string): Promise<void>;
  createTemporaryArchiveDirectory(): Promise<FirstPartyMicrosandboxTemporaryArchive>;
  writeImportRecord(
    record: FirstPartyMicrosandboxImageCandidateImportRecord,
  ): Promise<void>;
}

export interface FirstPartyMicrosandboxImageCandidateImportPlan {
  readonly schemaVersion:
    typeof FIRST_PARTY_MICROSANDBOX_IMAGE_CANDIDATE_IMPORT_PLAN_SCHEMA;
  readonly mode: "plan";
  readonly mutation: false;
  readonly physicalImageId: string;
  readonly oci: FirstPartyMicrosandboxImageCandidateReceipt["candidate"]["oci"];
  readonly plannedPull: string;
  /** Exact staging tag is generated only when this plan is executed. */
  readonly staging: {
    readonly strategy: "generated-at-run";
    readonly repository: string;
    readonly tagPrefix: string;
  };
  readonly plannedCandidateName: string;
  readonly microsandboxManifestDigest: "unobserved";
  readonly qualificationTarget: FirstPartyMicrosandboxImageCandidateReceipt[
    "candidate"
  ]["qualificationTarget"];
  readonly artifactCompliance: {
    readonly licence: "unresolved";
    readonly anonymousPull: "not-run";
    readonly runtimeQualification: "not-run";
    readonly eligibleForPromotion: false;
  };
}

export function firstPartyMicrosandboxImageCandidateStagingReference(
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
  stagingToken: string,
): string {
  assertStagingToken(stagingToken);
  const tag = `${stagingLocatorPrefix(receipt)}-${stagingToken}`;
  if (!DOCKER_TAG.test(tag)) {
    throw new TypeError(
      "First-party candidate staging tag must be a valid Docker tag.",
    );
  }
  return `${STAGING_REPOSITORY_PREFIX}${receipt.candidate.physicalImageId}:${tag}`;
}

export function planFirstPartyMicrosandboxImageCandidateImport(
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
): FirstPartyMicrosandboxImageCandidateImportPlan {
  assertLiteralNotRunCompliance(receipt);
  return Object.freeze({
    schemaVersion: FIRST_PARTY_MICROSANDBOX_IMAGE_CANDIDATE_IMPORT_PLAN_SCHEMA,
    mode: "plan",
    mutation: false,
    physicalImageId: receipt.candidate.physicalImageId,
    oci: receipt.candidate.oci,
    plannedPull: receipt.candidate.oci.platformManifestReference,
    staging: Object.freeze({
      strategy: "generated-at-run" as const,
      repository: `${STAGING_REPOSITORY_PREFIX}${receipt.candidate.physicalImageId}`,
      tagPrefix: `${stagingLocatorPrefix(receipt)}-`,
    }),
    plannedCandidateName: firstPartyMicrosandboxImageCandidateName(
      receipt.candidate.physicalImageId,
    ),
    microsandboxManifestDigest: "unobserved",
    qualificationTarget: receipt.candidate.qualificationTarget,
    artifactCompliance: Object.freeze({
      licence: "unresolved" as const,
      anonymousPull: "not-run" as const,
      runtimeQualification: "not-run" as const,
      eligibleForPromotion: false as const,
    }),
  });
}

export async function importFirstPartyMicrosandboxImageCandidate(input: {
  readonly receipt: FirstPartyMicrosandboxImageCandidateReceipt;
  readonly matrix: FirstPartyMicrosandboxImageDistributionMatrix;
  readonly ports: FirstPartyMicrosandboxImageCandidateImportPorts;
}): Promise<FirstPartyMicrosandboxImageCandidateImportRecord> {
  const receipt = await readBoundFirstPartyMicrosandboxImageCandidateReceipt(
    deterministicJson(input.receipt),
    input.matrix,
  );
  const ports = input.ports;
  assertLiteralNotRunCompliance(receipt);
  assertHostArchitecture(ports.hostArchitecture);
  const catalogPin = receipt.candidate.qualificationTarget.imageReference;
  const stagingToken = ports.createStagingToken();
  const stagingReference = firstPartyMicrosandboxImageCandidateStagingReference(
    receipt,
    stagingToken,
  );
  assertDistinctFromCatalogPin(stagingReference, catalogPin, "staging reference");
  const preexistingStaging = await lookupCachedRuntimeImage(
    ports,
    stagingReference,
  );
  if (preexistingStaging !== undefined) {
    throw new Error(
      "The invocation-owned first-party Microsandbox staging reference already exists.",
    );
  }

  const rawIndex = await ports.inspectOciIndex(receipt.candidate.oci.indexReference);
  await assertExactLinuxArm64OciIndex(rawIndex, receipt);
  await ports.pullByDigest(receipt.candidate.oci.platformManifestReference);
  const dockerInspection = parseDockerSourceInspection(
    await requireDockerInspection(
      ports,
      receipt.candidate.oci.platformManifestReference,
    ),
  );
  assertExactCandidateDockerSource(dockerInspection, receipt);

  let stagingLoaded = false;
  let importedFinalReference: string | undefined;
  let observedDigest: string | undefined;
  let recordWritten = false;
  let archiveCleaned = false;
  const temporary = await ports.createTemporaryArchiveDirectory();
  try {
    assertAllowedFirstPartyBootstrapTempPath(temporary.directory);
    const archivePath = assertAllowedFirstPartyBootstrapTempPath(
      temporary.archivePath,
    );
    await ports.saveDockerImage(
      receipt.candidate.oci.platformManifestReference,
      archivePath,
    );
    assertNonCatalogLoadTag(stagingReference, catalogPin);
    const stagingHandles = await ports.loadImageFromArchive(
      archivePath,
      stagingReference,
    );
    assertRequestedLoadReference(stagingHandles, stagingReference, "staging");
    stagingLoaded = true;
    assertNoCatalogPinReturnedByLoad(stagingHandles, catalogPin);
    const staged = await ports.inspectCachedImage(stagingReference);
    observedDigest = assertExactCandidateMicrosandboxInspection(
      staged,
      receipt,
      stagingReference,
      undefined,
    );
    const candidateReference = firstPartyMicrosandboxImageCandidateReference(
      receipt.candidate.physicalImageId,
      observedDigest,
    );
    const candidateCacheReference = firstPartyMicrosandboxImageCandidateCacheReference(
      receipt.candidate.physicalImageId,
      observedDigest,
    );
    assertDistinctFromCatalogPin(
      candidateReference,
      catalogPin,
      "final candidate reference",
    );
    assertDistinctFromCatalogPin(
      candidateCacheReference,
      catalogPin,
      "final candidate cache reference",
    );
    const preexisting = await lookupCachedRuntimeImage(
      ports,
      candidateCacheReference,
    );
    if (preexisting !== undefined) {
      try {
        assertExactCandidateMicrosandboxInspection(
          preexisting,
          receipt,
          candidateCacheReference,
          observedDigest,
        );
      } catch (error) {
        throw wrapIncoherentPreexistingCandidate(error);
      }
    }
    await removeOwnedCandidateReference(
      ports,
      receipt,
      stagingReference,
      stagingReference,
      observedDigest,
    );
    stagingLoaded = false;
    if (preexisting === undefined) {
      assertNonCatalogLoadTag(candidateCacheReference, catalogPin);
      const candidateHandles = await ports.loadImageFromArchive(
        archivePath,
        candidateCacheReference,
      );
      assertRequestedLoadReference(
        candidateHandles,
        candidateCacheReference,
        "final candidate",
      );
      importedFinalReference = candidateCacheReference;
      assertNoCatalogPinReturnedByLoad(candidateHandles, catalogPin);
    }
    const imported = await lookupCachedRuntimeImage(
      ports,
      candidateCacheReference,
    );
    if (imported === undefined) {
      throw new Error(
        "The cached first-party Microsandbox candidate is absent after import.",
      );
    }
    assertExactCandidateMicrosandboxInspection(
      imported,
      receipt,
      candidateCacheReference,
      observedDigest,
    );
    const record = await buildFirstPartyMicrosandboxImageCandidateImportRecord({
      receipt,
      microsandboxManifestDigest: observedDigest,
      status: preexisting === undefined ? "imported" : "already-cached",
    });
    await ports.writeImportRecord(record);
    recordWritten = true;
    await temporary.cleanup();
    archiveCleaned = true;
    return record;
  } catch (primary) {
    const cleanupErrors: unknown[] = [];
    if (!recordWritten && importedFinalReference !== undefined) {
      try {
        await removeOwnedCandidateReference(
          ports,
          receipt,
          stagingReference,
          importedFinalReference,
          observedDigest,
        );
      } catch (cleanupError) {
        cleanupErrors.push(cleanupError);
      }
    }
    if (stagingLoaded) {
      try {
        await removeOwnedCandidateReference(
          ports,
          receipt,
          stagingReference,
          stagingReference,
          observedDigest,
        );
        stagingLoaded = false;
      } catch (cleanupError) {
        cleanupErrors.push(cleanupError);
      }
    }
    if (!archiveCleaned) {
      try {
        await temporary.cleanup();
        archiveCleaned = true;
      } catch (cleanupError) {
        cleanupErrors.push(cleanupError);
      }
    }
    if (cleanupErrors.length > 0) {
      throw new AggregateError(
        [primary, ...cleanupErrors],
        "First-party candidate import failed and staging or archive cleanup also failed.",
        { cause: primary },
      );
    }
    throw primary;
  }
}

export function renderFirstPartyMicrosandboxImageCandidateImportPlanText(
  plan: FirstPartyMicrosandboxImageCandidateImportPlan,
): string {
  return [
    `schemaVersion=${plan.schemaVersion}`,
    `mode=${plan.mode}`,
    `mutation=${plan.mutation}`,
    `physicalImageId=${plan.physicalImageId}`,
    `oci.indexDigest=${plan.oci.indexDigest}`,
    `oci.platformManifestDigest=${plan.oci.platformManifestDigest}`,
    `plannedPull=${plan.plannedPull}`,
    `staging.strategy=${plan.staging.strategy}`,
    `staging.repository=${plan.staging.repository}`,
    `staging.tagPrefix=${plan.staging.tagPrefix}`,
    `plannedCandidateName=${plan.plannedCandidateName}`,
    `microsandboxManifestDigest=${plan.microsandboxManifestDigest}`,
    `qualificationTarget.imageReference=${plan.qualificationTarget.imageReference}`,
    `runtimeQualification=${plan.artifactCompliance.runtimeQualification}`,
    `eligibleForPromotion=${plan.artifactCompliance.eligibleForPromotion}`,
    "Domain qualification remains not-run. Promotion is false.",
    "",
  ].join("\n");
}

async function assertExactLinuxArm64OciIndex(
  rawIndex: string,
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
): Promise<void> {
  const matchedRaw = await matchingOciIndexBytes(
    rawIndex,
    receipt.candidate.oci.indexDigest,
  );
  if (matchedRaw === undefined) {
    throw new Error(
      "The inspected OCI index digest is not the receipt OCI index digest.",
    );
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(matchedRaw);
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new TypeError(`OCI index must be valid JSON: ${detail}`);
  }
  const root = jsonObject(parsed, "OCI index");
  const manifests = root.manifests;
  if (!Array.isArray(manifests)) {
    throw new TypeError("OCI index manifests must be an array.");
  }
  const arm64 = manifests.filter((item) => {
    if (item === null || typeof item !== "object" || Array.isArray(item)) {
      return false;
    }
    const platform = (item as Record<string, unknown>).platform;
    if (
      platform === null || typeof platform !== "object" || Array.isArray(platform)
    ) {
      return false;
    }
    const body = platform as Record<string, unknown>;
    return body.os === "linux" && body.architecture === "arm64";
  });
  if (arm64.length !== 1) {
    throw new Error(
      "OCI index must contain exactly one linux/arm64 child manifest.",
    );
  }
  const child = arm64[0] as Record<string, unknown>;
  if (child.digest !== receipt.candidate.oci.platformManifestDigest) {
    throw new Error(
      "The OCI index linux/arm64 child digest is not the receipt platform-manifest digest.",
    );
  }
}

function assertExactCandidateDockerSource(
  inspection: DockerSourceInspection,
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
): void {
  const expected = receipt.candidate.expectedRuntime;
  const digestMatches = inspection.repoDigests.some((digest) =>
    samePinnedRepositoryDigest(
      digest,
      receipt.candidate.oci.platformManifestReference,
    )
  );
  if (
    inspection.os !== "linux" ||
    inspection.architecture !== "arm64" ||
    inspection.user !== expected.user ||
    !stringArraysEqual(inspection.entrypoint, expected.entrypoint) ||
    !digestMatches ||
    (expected.labels !== undefined &&
      !Object.entries(expected.labels).every(([name, value]) =>
        inspection.labels[name] === value
      ))
  ) {
    throw new Error(
      "The Docker source image is not the exact linux/arm64 first-party candidate.",
    );
  }
}

function assertExactCandidateMicrosandboxInspection(
  image: MicrosandboxImageInspection,
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
  expectedReference: string,
  expectedDigest: string | undefined,
): string {
  const expected = receipt.candidate.expectedRuntime;
  if (!SHA256.test(image.manifestDigest)) {
    throw new Error(
      "The cached Microsandbox candidate is not identified by a lowercase sha256 digest.",
    );
  }
  if (
    image.reference !== expectedReference ||
    image.os !== "linux" ||
    image.architecture !== "arm64" ||
    image.user !== expected.user ||
    !stringArraysEqual(image.entrypoint, expected.entrypoint) ||
    (expectedDigest !== undefined && image.manifestDigest !== expectedDigest)
  ) {
    throw new Error(
      "The cached Microsandbox candidate is not the inspected first-party candidate.",
    );
  }
  return image.manifestDigest;
}

async function matchingOciIndexBytes(
  rawIndex: string,
  expectedDigest: string,
): Promise<string | undefined> {
  const candidates = rawIndex.endsWith("\n")
    ? [rawIndex, rawIndex.slice(0, -1)]
    : [rawIndex];
  for (const candidate of candidates) {
    const digest = `sha256:${await sha256Hex(new TextEncoder().encode(candidate))}`;
    if (digest === expectedDigest) return candidate;
  }
  return undefined;
}

async function requireDockerInspection(
  ports: FirstPartyMicrosandboxImageCandidateImportPorts,
  reference: string,
): Promise<unknown> {
  const raw = await ports.inspectDockerImage(reference);
  if (raw === undefined) {
    throw new Error("The Docker platform-manifest image is absent after pull.");
  }
  return raw;
}

async function lookupCachedRuntimeImage(
  ports: FirstPartyMicrosandboxImageCandidateImportPorts,
  reference: string,
): Promise<MicrosandboxImageInspection | undefined> {
  try {
    return await ports.inspectCachedImage(reference);
  } catch (error) {
    if (ports.isImageNotFound(error)) return undefined;
    throw error;
  }
}

async function removeOwnedCandidateReference(
  ports: FirstPartyMicrosandboxImageCandidateImportPorts,
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
  stagingReference: string,
  reference: string,
  observedDigest: string | undefined,
): Promise<void> {
  assertOwnedCandidateCacheReference(
    reference,
    receipt,
    stagingReference,
    observedDigest,
  );
  await ports.removeExactCachedImage(reference);
}

function wrapIncoherentPreexistingCandidate(error: unknown): Error {
  const detail = error instanceof Error ? error.message : String(error);
  return new Error(
    `An incoherent pre-existing first-party Microsandbox candidate must not be deleted: ${detail}`,
  );
}

function firstPartyMicrosandboxImageCandidateCacheReference(
  physicalImageId: string,
  microsandboxManifestDigest: string,
): string {
  return pinnedOciImageReference(
    firstPartyMicrosandboxImageCandidateReference(
      physicalImageId,
      microsandboxManifestDigest,
    ),
    "$firstPartyCandidateImport.microsandbox.cacheReference",
  );
}

function assertOwnedCandidateCacheReference(
  reference: string,
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
  stagingReference: string,
  observedDigest: string | undefined,
): void {
  const catalogPin = receipt.candidate.qualificationTarget.imageReference;
  if (isActiveCataloguePin(reference, catalogPin)) {
    throw new Error(
      "First-party candidate import must not remove the active catalogue pin.",
    );
  }
  if (reference === stagingReference) return;
  if (observedDigest === undefined) {
    throw new Error(
      "First-party candidate import may remove only its staging or final candidate reference.",
    );
  }
  const expectedCacheReference = firstPartyMicrosandboxImageCandidateCacheReference(
    receipt.candidate.physicalImageId,
    observedDigest,
  );
  if (reference !== expectedCacheReference) {
    throw new Error(
      "First-party candidate import may remove only its staging or final candidate reference.",
    );
  }
}

function assertNonCatalogLoadTag(tag: string, catalogPin: string): void {
  if (isActiveCataloguePin(tag, catalogPin)) {
    throw new Error(
      "First-party candidate import must not load under the active catalogue pin.",
    );
  }
}

function assertRequestedLoadReference(
  handles: readonly MicrosandboxImageImportHandle[],
  expectedReference: string,
  role: "staging" | "final candidate",
): void {
  if (!handles.some((handle) => handle.reference === expectedReference)) {
    throw new Error(
      `Microsandbox archive load did not apply the requested ${role} reference.`,
    );
  }
}

function assertNoCatalogPinReturnedByLoad(
  handles: readonly MicrosandboxImageImportHandle[],
  catalogPin: string,
): void {
  if (handles.some((handle) => isActiveCataloguePin(handle.reference, catalogPin))) {
    throw new Error(
      "Microsandbox archive load returned the active catalogue pin; the candidate import is refused.",
    );
  }
}

function assertDistinctFromCatalogPin(
  reference: string,
  catalogPin: string,
  label: string,
): void {
  if (isActiveCataloguePin(reference, catalogPin)) {
    throw new Error(
      `First-party candidate ${label} must not equal the active catalogue pin.`,
    );
  }
}

function isActiveCataloguePin(reference: string, catalogPin: string): boolean {
  return reference === catalogPin ||
    samePinnedRepositoryDigest(reference, catalogPin);
}

function assertLiteralNotRunCompliance(
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
): void {
  if (
    receipt.artifactCompliance.runtimeQualification !== "not-run" ||
    receipt.artifactCompliance.eligibleForPromotion !== false
  ) {
    throw new TypeError(
      "Candidate import requires runtimeQualification=not-run and eligibleForPromotion=false.",
    );
  }
}

function assertHostArchitecture(hostArchitecture: string): void {
  if (hostArchitecture !== "arm64") {
    throw new Error(
      "First-party Microsandbox candidate import is reviewed only for native linux/arm64.",
    );
  }
}

function assertStagingToken(value: string): void {
  if (!STAGING_TOKEN.test(value)) {
    throw new TypeError(
      "First-party candidate staging token must be a server-generated lowercase nonce.",
    );
  }
}

function stagingLocatorPrefix(
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
): string {
  return receipt.candidate.locatorTag.slice(
    0,
    MAXIMUM_STAGING_LOCATOR_PREFIX_LENGTH,
  );
}

function jsonObject(value: unknown, label: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`${label} must be a JSON object.`);
  }
  return value as Record<string, unknown>;
}

function stringArraysEqual(
  left: readonly string[] | null,
  right: readonly string[],
): boolean {
  return left !== null && left.length === right.length &&
    left.every((value, index) => value === right[index]);
}
