/**
 * Maintainer-only import/inspection of one first-party Microsandbox image
 * candidate. The only identity input is an exact repository receipt already
 * bound to the current server-owned distribution matrix.
 *
 * Three immutable provenance fields stay separately recorded:
 * 1. OCI index digest from Buildx
 * 2. linux/arm64 OCI platform-manifest digest pulled from Docker
 * 3. Microsandbox manifest digest observed after docker save + Image.load
 *
 * Their hash text can coincide; neither a comparison nor a record collapses
 * the three provenance fields into one identity.
 *
 * This path never calls acquireFirstPartyMicrosandboxImage (that imports under
 * the active catalogue pin). Microsandbox SDK 0.6.8 has no tag/relabel API:
 * staging is Image.load(archive, { tag: staging }), then exact Image.remove of
 * that staging reference, then a second Image.load of the same archive with
 * tag casys/first-party-candidate-<physicalImageId>@sha256:<observed-msb-digest>.
 * That second load is a re-import that applies the candidate reference, not an
 * in-place retag.
 */

import { samePinnedRepositoryDigest } from "../shared/docker-pinned-repository-digest.ts";
import {
  createLocalMicrosandboxSdk,
  loadLocalMicrosandboxImageImportHandlesFromArchive,
  microsandboxHostArchitecture,
  type MicrosandboxImageImportHandle,
  type MicrosandboxImageInspection,
  type MicrosandboxSdk,
} from "../shared/execution/microsandbox-ephemeral-execution-backend.ts";
import {
  deterministicJson,
  sha256Hex,
} from "../../domain/kernel/deterministic-json.ts";
import {
  assertAllowedFirstPartyBootstrapTempPath,
  type DockerSourceInspection,
  type FirstPartyMicrosandboxTemporaryArchive,
  parseDockerSourceInspection,
} from "./first-party-microsandbox-image-acquisition.ts";
import type { FirstPartyMicrosandboxImageCandidateReceipt } from "./first-party-microsandbox-image-candidate-receipt.ts";

export const FIRST_PARTY_MICROSANDBOX_IMAGE_CANDIDATE_IMPORT_RECORD_SCHEMA =
  "first-party-microsandbox-image-candidate-import/2.0" as const;

export const FIRST_PARTY_MICROSANDBOX_IMAGE_CANDIDATE_IMPORT_PLAN_SCHEMA =
  "first-party-microsandbox-image-candidate-import-plan/2.0" as const;

export const FIRST_PARTY_MICROSANDBOX_IMAGE_CANDIDATE_IMPORT_RECORD_DIRECTORY =
  "state/local/first-party-microsandbox-image-candidate-import" as const;

const SHA256 = /^sha256:[0-9a-f]{64}$/u;
const PULL_POLICY_NEVER = "never" as const;
const CANDIDATE_REPOSITORY_PREFIX = "casys/first-party-candidate-" as const;
const STAGING_REPOSITORY_PREFIX = "casys/first-party-candidate-staging-" as const;
const STAGING_TOKEN = /^[a-z0-9](?:[a-z0-9-]{0,63})?$/u;
const DOCKER_TAG = /^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$/u;
const MAXIMUM_STAGING_LOCATOR_PREFIX_LENGTH = 63;

export interface FirstPartyMicrosandboxImageCandidateImportPorts {
  readonly hostArchitecture: string;
  /**
   * Invocation-owned nonce. It is generated by the server/composition at run
   * time, never supplied by a caller and never persisted in the factual
   * candidate record.
   */
  createStagingToken(): string;
  inspectOciIndex(reference: string): Promise<string>;
  pullByDigest(reference: string): Promise<void>;
  inspectDockerImage(reference: string): Promise<unknown | undefined>;
  saveDockerImage(reference: string, archivePath: string): Promise<void>;
  loadImageFromArchive(
    archivePath: string,
    tag: string,
  ): Promise<readonly MicrosandboxImageImportHandle[]>;
  inspectCachedImage(reference: string): Promise<MicrosandboxImageInspection>;
  isImageNotFound(error: unknown): boolean;
  /**
   * Exact Microsandbox cached-image removal. No force, prune, or volume.
   * Callers of this port from the candidate-import flow may pass only the
   * staging reference or a final candidate this flow just imported.
   */
  removeExactCachedImage(reference: string): Promise<void>;
  createTemporaryArchiveDirectory(): Promise<FirstPartyMicrosandboxTemporaryArchive>;
  writeImportRecord(
    record: FirstPartyMicrosandboxImageCandidateImportRecord,
  ): Promise<void>;
}

export interface FirstPartyMicrosandboxImageCandidateImportPlan {
  readonly schemaVersion:
    typeof FIRST_PARTY_MICROSANDBOX_IMAGE_CANDIDATE_IMPORT_PLAN_SCHEMA;
  readonly mode: "plan";
  readonly mutation: false;
  readonly physicalImageId: string;
  readonly oci: FirstPartyMicrosandboxImageCandidateReceipt["candidate"]["oci"];
  readonly plannedPull: string;
  /** Exact staging tag is generated only when this plan is executed. */
  readonly staging: {
    readonly strategy: "generated-at-run";
    readonly repository: string;
    readonly tagPrefix: string;
  };
  readonly plannedCandidateName: string;
  readonly microsandboxManifestDigest: "unobserved";
  readonly qualificationTarget: FirstPartyMicrosandboxImageCandidateReceipt[
    "candidate"
  ]["qualificationTarget"];
  readonly artifactCompliance: {
    readonly licence: "unresolved";
    readonly anonymousPull: "not-run";
    readonly runtimeQualification: "not-run";
    readonly eligibleForPromotion: false;
  };
}

export interface FirstPartyMicrosandboxImageCandidateImportRecord {
  readonly schemaVersion:
    typeof FIRST_PARTY_MICROSANDBOX_IMAGE_CANDIDATE_IMPORT_RECORD_SCHEMA;
  readonly candidate: {
    readonly physicalImageId: string;
    readonly imageName: string;
    readonly oci: FirstPartyMicrosandboxImageCandidateReceipt["candidate"]["oci"];
    readonly microsandbox: {
      readonly candidateReference: string;
      readonly manifestDigest: string;
    };
    readonly locatorTag: string;
    readonly locatorReference: string;
    readonly git: FirstPartyMicrosandboxImageCandidateReceipt["candidate"]["git"];
    readonly qualificationTarget: FirstPartyMicrosandboxImageCandidateReceipt[
      "candidate"
    ]["qualificationTarget"];
  };
  readonly identities: {
    readonly ociIndexDigest: string;
    readonly ociPlatformManifestDigest: string;
    readonly microsandboxManifestDigest: string;
  };
  readonly inputMatrix: {
    readonly fingerprint: string;
    readonly schemaVersion: FirstPartyMicrosandboxImageCandidateReceipt[
      "inputMatrix"
    ]["schemaVersion"];
  };
  readonly artifactCompliance: {
    readonly licence: "unresolved";
    readonly anonymousPull: "not-run";
    readonly runtimeQualification: "not-run";
    readonly eligibleForPromotion: false;
    readonly sbom: "requested";
    readonly provenance: "requested";
  };
  readonly import: {
    readonly status: "imported" | "already-cached";
    readonly hostArchitecture: "arm64";
    readonly pullPolicy: typeof PULL_POLICY_NEVER;
  };
}

export function firstPartyMicrosandboxImageCandidateStagingReference(
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
  stagingToken: string,
): string {
  assertStagingToken(stagingToken);
  const tag = `${stagingLocatorPrefix(receipt)}-${stagingToken}`;
  if (!DOCKER_TAG.test(tag)) {
    throw new TypeError(
      "First-party candidate staging tag must be a valid Docker tag.",
    );
  }
  return `${STAGING_REPOSITORY_PREFIX}${receipt.candidate.physicalImageId}:${tag}`;
}

export function firstPartyMicrosandboxImageCandidateName(
  physicalImageId: string,
): string {
  return `${CANDIDATE_REPOSITORY_PREFIX}${physicalImageId}`;
}

export function firstPartyMicrosandboxImageCandidateReference(
  physicalImageId: string,
  microsandboxManifestDigest: string,
): string {
  assertSha256(microsandboxManifestDigest, "candidate Microsandbox manifest digest");
  return `${
    firstPartyMicrosandboxImageCandidateName(physicalImageId)
  }@${microsandboxManifestDigest}`;
}

export function planFirstPartyMicrosandboxImageCandidateImport(
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
): FirstPartyMicrosandboxImageCandidateImportPlan {
  assertLiteralNotRunCompliance(receipt);
  return Object.freeze({
    schemaVersion: FIRST_PARTY_MICROSANDBOX_IMAGE_CANDIDATE_IMPORT_PLAN_SCHEMA,
    mode: "plan",
    mutation: false,
    physicalImageId: receipt.candidate.physicalImageId,
    oci: receipt.candidate.oci,
    plannedPull: receipt.candidate.oci.platformManifestReference,
    staging: Object.freeze({
      strategy: "generated-at-run" as const,
      repository: `${STAGING_REPOSITORY_PREFIX}${receipt.candidate.physicalImageId}`,
      tagPrefix: `${stagingLocatorPrefix(receipt)}-`,
    }),
    plannedCandidateName: firstPartyMicrosandboxImageCandidateName(
      receipt.candidate.physicalImageId,
    ),
    microsandboxManifestDigest: "unobserved",
    qualificationTarget: receipt.candidate.qualificationTarget,
    artifactCompliance: Object.freeze({
      licence: "unresolved" as const,
      anonymousPull: "not-run" as const,
      runtimeQualification: "not-run" as const,
      eligibleForPromotion: false as const,
    }),
  });
}

export async function importFirstPartyMicrosandboxImageCandidate(input: {
  readonly receipt: FirstPartyMicrosandboxImageCandidateReceipt;
  readonly ports: FirstPartyMicrosandboxImageCandidateImportPorts;
}): Promise<FirstPartyMicrosandboxImageCandidateImportRecord> {
  const receipt = input.receipt;
  const ports = input.ports;
  assertLiteralNotRunCompliance(receipt);
  assertHostArchitecture(ports.hostArchitecture);
  const catalogPin = receipt.candidate.qualificationTarget.imageReference;
  const stagingToken = ports.createStagingToken();
  const stagingReference = firstPartyMicrosandboxImageCandidateStagingReference(
    receipt,
    stagingToken,
  );
  assertDistinctFromCatalogPin(stagingReference, catalogPin, "staging reference");
  const preexistingStaging = await lookupCachedRuntimeImage(
    ports,
    stagingReference,
  );
  if (preexistingStaging !== undefined) {
    throw new Error(
      "The invocation-owned first-party Microsandbox staging reference already exists.",
    );
  }

  const rawIndex = await ports.inspectOciIndex(receipt.candidate.oci.indexReference);
  await assertExactLinuxArm64OciIndex(rawIndex, receipt);
  await ports.pullByDigest(receipt.candidate.oci.platformManifestReference);
  const dockerInspection = parseDockerSourceInspection(
    await requireDockerInspection(
      ports,
      receipt.candidate.oci.platformManifestReference,
    ),
  );
  assertExactCandidateDockerSource(dockerInspection, receipt);

  let stagingLoaded = false;
  let importedFinalReference: string | undefined;
  let recordWritten = false;
  let archiveCleaned = false;
  const temporary = await ports.createTemporaryArchiveDirectory();
  try {
    assertAllowedFirstPartyBootstrapTempPath(temporary.directory);
    const archivePath = assertAllowedFirstPartyBootstrapTempPath(
      temporary.archivePath,
    );
    await ports.saveDockerImage(
      receipt.candidate.oci.platformManifestReference,
      archivePath,
    );
    assertNonCatalogLoadTag(stagingReference, catalogPin);
    const stagingHandles = await ports.loadImageFromArchive(
      archivePath,
      stagingReference,
    );
    assertRequestedLoadReference(stagingHandles, stagingReference, "staging");
    stagingLoaded = true;
    assertNoCatalogPinReturnedByLoad(stagingHandles, catalogPin);
    const staged = await ports.inspectCachedImage(stagingReference);
    const observedDigest = assertExactCandidateMicrosandboxInspection(
      staged,
      receipt,
      stagingReference,
      undefined,
    );
    const candidateReference = firstPartyMicrosandboxImageCandidateReference(
      receipt.candidate.physicalImageId,
      observedDigest,
    );
    assertDistinctFromCatalogPin(
      candidateReference,
      catalogPin,
      "final candidate reference",
    );
    const preexisting = await lookupCachedRuntimeImage(ports, candidateReference);
    if (preexisting !== undefined) {
      try {
        assertExactCandidateMicrosandboxInspection(
          preexisting,
          receipt,
          candidateReference,
          observedDigest,
        );
      } catch (error) {
        throw wrapIncoherentPreexistingCandidate(error);
      }
    }
    await removeOwnedCandidateReference(
      ports,
      receipt,
      stagingReference,
      stagingReference,
    );
    stagingLoaded = false;
    if (preexisting === undefined) {
      assertNonCatalogLoadTag(candidateReference, catalogPin);
      const candidateHandles = await ports.loadImageFromArchive(
        archivePath,
        candidateReference,
      );
      assertRequestedLoadReference(
        candidateHandles,
        candidateReference,
        "final candidate",
      );
      importedFinalReference = candidateReference;
      assertNoCatalogPinReturnedByLoad(candidateHandles, catalogPin);
    }
    const imported = await lookupCachedRuntimeImage(ports, candidateReference);
    if (imported === undefined) {
      throw new Error(
        "The cached first-party Microsandbox candidate is absent after import.",
      );
    }
    assertExactCandidateMicrosandboxInspection(
      imported,
      receipt,
      candidateReference,
      observedDigest,
    );
    const record = buildImportRecord(receipt, {
      candidateReference,
      manifestDigest: observedDigest,
      status: preexisting === undefined ? "imported" : "already-cached",
    });
    await ports.writeImportRecord(record);
    recordWritten = true;
    await temporary.cleanup();
    archiveCleaned = true;
    return record;
  } catch (primary) {
    const cleanupErrors: unknown[] = [];
    if (!recordWritten && importedFinalReference !== undefined) {
      try {
        await removeOwnedCandidateReference(
          ports,
          receipt,
          stagingReference,
          importedFinalReference,
        );
      } catch (cleanupError) {
        cleanupErrors.push(cleanupError);
      }
    }
    if (stagingLoaded) {
      try {
        await removeOwnedCandidateReference(
          ports,
          receipt,
          stagingReference,
          stagingReference,
        );
        stagingLoaded = false;
      } catch (cleanupError) {
        cleanupErrors.push(cleanupError);
      }
    }
    if (!archiveCleaned) {
      try {
        await temporary.cleanup();
        archiveCleaned = true;
      } catch (cleanupError) {
        cleanupErrors.push(cleanupError);
      }
    }
    if (cleanupErrors.length > 0) {
      throw new AggregateError(
        [primary, ...cleanupErrors],
        "First-party candidate import failed and staging or archive cleanup also failed.",
        { cause: primary },
      );
    }
    throw primary;
  }
}

export async function createLocalFirstPartyMicrosandboxImageCandidateImportPorts(
  createSdk: () => Promise<MicrosandboxSdk> = createLocalMicrosandboxSdk,
): Promise<FirstPartyMicrosandboxImageCandidateImportPorts> {
  const sdk = await createSdk();
  sdk.assertLocalBackend();
  return Object.freeze({
    hostArchitecture: microsandboxHostArchitecture(),
    createStagingToken: createFirstPartyMicrosandboxImageCandidateStagingToken,
    inspectOciIndex,
    pullByDigest,
    inspectDockerImage,
    saveDockerImage,
    loadImageFromArchive: (archivePath: string, tag: string) =>
      loadLocalMicrosandboxImageImportHandlesFromArchive(archivePath, tag),
    inspectCachedImage: (reference: string) => sdk.inspectImage(reference),
    isImageNotFound: (error: unknown) => sdk.isImageNotFound(error),
    removeExactCachedImage: (reference: string) =>
      sdk.removeExactCachedImage(reference),
    createTemporaryArchiveDirectory: createAllowedCandidateArchive,
    writeImportRecord: writeFirstPartyMicrosandboxImageCandidateImportRecord,
  });
}

export async function writeFirstPartyMicrosandboxImageCandidateImportRecord(
  record: FirstPartyMicrosandboxImageCandidateImportRecord,
  root: string = FIRST_PARTY_MICROSANDBOX_IMAGE_CANDIDATE_IMPORT_RECORD_DIRECTORY,
): Promise<void> {
  const text = `${deterministicJson(record)}\n`;
  const directory = `${root}/${record.candidate.physicalImageId}`;
  await Deno.mkdir(directory, { recursive: true });
  const path = `${directory}/${importRecordFileName(record)}`;
  try {
    await Deno.writeTextFile(path, text, { createNew: true });
  } catch (error) {
    if (error instanceof Deno.errors.AlreadyExists) {
      const existing = await Deno.readTextFile(path);
      if (existing === text) return;
      throw new Error(
        "An incoherent first-party candidate import record already exists.",
      );
    }
    throw error;
  }
}

export function renderFirstPartyMicrosandboxImageCandidateImportPlanText(
  plan: FirstPartyMicrosandboxImageCandidateImportPlan,
): string {
  return [
    `schemaVersion=${plan.schemaVersion}`,
    `mode=${plan.mode}`,
    `mutation=${plan.mutation}`,
    `physicalImageId=${plan.physicalImageId}`,
    `oci.indexDigest=${plan.oci.indexDigest}`,
    `oci.platformManifestDigest=${plan.oci.platformManifestDigest}`,
    `plannedPull=${plan.plannedPull}`,
    `staging.strategy=${plan.staging.strategy}`,
    `staging.repository=${plan.staging.repository}`,
    `staging.tagPrefix=${plan.staging.tagPrefix}`,
    `plannedCandidateName=${plan.plannedCandidateName}`,
    `microsandboxManifestDigest=${plan.microsandboxManifestDigest}`,
    `qualificationTarget.imageReference=${plan.qualificationTarget.imageReference}`,
    `runtimeQualification=${plan.artifactCompliance.runtimeQualification}`,
    `eligibleForPromotion=${plan.artifactCompliance.eligibleForPromotion}`,
    "Domain qualification remains not-run. Promotion is false.",
    "",
  ].join("\n");
}

export function renderFirstPartyMicrosandboxImageCandidateImportRecordText(
  record: FirstPartyMicrosandboxImageCandidateImportRecord,
): string {
  return [
    `schemaVersion=${record.schemaVersion}`,
    `status=${record.import.status}`,
    `physicalImageId=${record.candidate.physicalImageId}`,
    `oci.indexDigest=${record.identities.ociIndexDigest}`,
    `oci.platformManifestDigest=${record.identities.ociPlatformManifestDigest}`,
    `microsandbox.manifestDigest=${record.identities.microsandboxManifestDigest}`,
    `microsandbox.candidateReference=${record.candidate.microsandbox.candidateReference}`,
    `qualificationTarget.imageReference=${record.candidate.qualificationTarget.imageReference}`,
    `runtimeQualification=${record.artifactCompliance.runtimeQualification}`,
    `eligibleForPromotion=${record.artifactCompliance.eligibleForPromotion}`,
    "Domain qualification remains not-run. Promotion is false.",
    "",
  ].join("\n");
}

async function assertExactLinuxArm64OciIndex(
  rawIndex: string,
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
): Promise<void> {
  const matchedRaw = await matchingOciIndexBytes(
    rawIndex,
    receipt.candidate.oci.indexDigest,
  );
  if (matchedRaw === undefined) {
    throw new Error(
      "The inspected OCI index digest is not the receipt OCI index digest.",
    );
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(matchedRaw);
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new TypeError(`OCI index must be valid JSON: ${detail}`);
  }
  const root = jsonObject(parsed, "OCI index");
  const manifests = root.manifests;
  if (!Array.isArray(manifests)) {
    throw new TypeError("OCI index manifests must be an array.");
  }
  const arm64 = manifests.filter((item) => {
    if (item === null || typeof item !== "object" || Array.isArray(item)) {
      return false;
    }
    const platform = (item as Record<string, unknown>).platform;
    if (
      platform === null || typeof platform !== "object" || Array.isArray(platform)
    ) {
      return false;
    }
    const body = platform as Record<string, unknown>;
    return body.os === "linux" && body.architecture === "arm64";
  });
  if (arm64.length !== 1) {
    throw new Error(
      "OCI index must contain exactly one linux/arm64 child manifest.",
    );
  }
  const child = arm64[0] as Record<string, unknown>;
  if (child.digest !== receipt.candidate.oci.platformManifestDigest) {
    throw new Error(
      "The OCI index linux/arm64 child digest is not the receipt platform-manifest digest.",
    );
  }
}

function assertExactCandidateDockerSource(
  inspection: DockerSourceInspection,
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
): void {
  const expected = receipt.candidate.expectedRuntime;
  const digestMatches = inspection.repoDigests.some((digest) =>
    samePinnedRepositoryDigest(
      digest,
      receipt.candidate.oci.platformManifestReference,
    )
  );
  if (
    inspection.os !== "linux" ||
    inspection.architecture !== "arm64" ||
    inspection.user !== expected.user ||
    !stringArraysEqual(inspection.entrypoint, expected.entrypoint) ||
    !digestMatches ||
    (expected.labels !== undefined &&
      !Object.entries(expected.labels).every(([name, value]) =>
        inspection.labels[name] === value
      ))
  ) {
    throw new Error(
      "The Docker source image is not the exact linux/arm64 first-party candidate.",
    );
  }
}

function assertExactCandidateMicrosandboxInspection(
  image: MicrosandboxImageInspection,
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
  expectedReference: string,
  expectedDigest: string | undefined,
): string {
  const expected = receipt.candidate.expectedRuntime;
  if (!SHA256.test(image.manifestDigest)) {
    throw new Error(
      "The cached Microsandbox candidate is not identified by a lowercase sha256 digest.",
    );
  }
  if (
    image.reference !== expectedReference ||
    image.os !== "linux" ||
    image.architecture !== "arm64" ||
    image.user !== expected.user ||
    !stringArraysEqual(image.entrypoint, expected.entrypoint) ||
    (expectedDigest !== undefined && image.manifestDigest !== expectedDigest)
  ) {
    throw new Error(
      "The cached Microsandbox candidate is not the inspected first-party candidate.",
    );
  }
  return image.manifestDigest;
}

function buildImportRecord(
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
  imported: {
    readonly candidateReference: string;
    readonly manifestDigest: string;
    readonly status: "imported" | "already-cached";
  },
): FirstPartyMicrosandboxImageCandidateImportRecord {
  return Object.freeze({
    schemaVersion: FIRST_PARTY_MICROSANDBOX_IMAGE_CANDIDATE_IMPORT_RECORD_SCHEMA,
    candidate: Object.freeze({
      physicalImageId: receipt.candidate.physicalImageId,
      imageName: receipt.candidate.imageName,
      oci: receipt.candidate.oci,
      microsandbox: Object.freeze({
        candidateReference: imported.candidateReference,
        manifestDigest: imported.manifestDigest,
      }),
      locatorTag: receipt.candidate.locatorTag,
      locatorReference: receipt.candidate.locatorReference,
      git: receipt.candidate.git,
      qualificationTarget: receipt.candidate.qualificationTarget,
    }),
    identities: Object.freeze({
      ociIndexDigest: receipt.candidate.oci.indexDigest,
      ociPlatformManifestDigest: receipt.candidate.oci.platformManifestDigest,
      microsandboxManifestDigest: imported.manifestDigest,
    }),
    inputMatrix: Object.freeze({
      fingerprint: receipt.inputMatrix.fingerprint,
      schemaVersion: receipt.inputMatrix.schemaVersion,
    }),
    artifactCompliance: Object.freeze({
      licence: "unresolved" as const,
      anonymousPull: "not-run" as const,
      runtimeQualification: "not-run" as const,
      eligibleForPromotion: false as const,
      sbom: "requested" as const,
      provenance: "requested" as const,
    }),
    import: Object.freeze({
      status: imported.status,
      hostArchitecture: "arm64" as const,
      pullPolicy: PULL_POLICY_NEVER,
    }),
  });
}

function importRecordFileName(
  record: FirstPartyMicrosandboxImageCandidateImportRecord,
): string {
  return [
    hexDigest(record.identities.ociIndexDigest),
    hexDigest(record.identities.ociPlatformManifestDigest),
    hexDigest(record.identities.microsandboxManifestDigest),
  ].join("-") + ".json";
}

function hexDigest(value: string): string {
  return value.slice("sha256:".length);
}

async function matchingOciIndexBytes(
  rawIndex: string,
  expectedDigest: string,
): Promise<string | undefined> {
  const candidates = rawIndex.endsWith("\n")
    ? [rawIndex, rawIndex.slice(0, -1)]
    : [rawIndex];
  for (const candidate of candidates) {
    const digest = `sha256:${await sha256Hex(new TextEncoder().encode(candidate))}`;
    if (digest === expectedDigest) return candidate;
  }
  return undefined;
}

async function requireDockerInspection(
  ports: FirstPartyMicrosandboxImageCandidateImportPorts,
  reference: string,
): Promise<unknown> {
  const raw = await ports.inspectDockerImage(reference);
  if (raw === undefined) {
    throw new Error("The Docker platform-manifest image is absent after pull.");
  }
  return raw;
}

async function lookupCachedRuntimeImage(
  ports: FirstPartyMicrosandboxImageCandidateImportPorts,
  reference: string,
): Promise<MicrosandboxImageInspection | undefined> {
  try {
    return await ports.inspectCachedImage(reference);
  } catch (error) {
    if (ports.isImageNotFound(error)) return undefined;
    throw error;
  }
}

async function removeOwnedCandidateReference(
  ports: FirstPartyMicrosandboxImageCandidateImportPorts,
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
  stagingReference: string,
  reference: string,
): Promise<void> {
  assertOwnedCandidateCacheReference(reference, receipt, stagingReference);
  await ports.removeExactCachedImage(reference);
}

function wrapIncoherentPreexistingCandidate(error: unknown): Error {
  const detail = error instanceof Error ? error.message : String(error);
  return new Error(
    `An incoherent pre-existing first-party Microsandbox candidate must not be deleted: ${detail}`,
  );
}

function assertOwnedCandidateCacheReference(
  reference: string,
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
  stagingReference: string,
): void {
  const catalogPin = receipt.candidate.qualificationTarget.imageReference;
  if (reference === catalogPin) {
    throw new Error(
      "First-party candidate import must not remove the active catalogue pin.",
    );
  }
  const candidatePrefix = `${
    firstPartyMicrosandboxImageCandidateName(receipt.candidate.physicalImageId)
  }@sha256:`;
  if (reference !== stagingReference && !reference.startsWith(candidatePrefix)) {
    throw new Error(
      "First-party candidate import may remove only its staging or final candidate reference.",
    );
  }
}

function assertNonCatalogLoadTag(tag: string, catalogPin: string): void {
  if (tag === catalogPin) {
    throw new Error(
      "First-party candidate import must not load under the active catalogue pin.",
    );
  }
}

function assertRequestedLoadReference(
  handles: readonly MicrosandboxImageImportHandle[],
  expectedReference: string,
  role: "staging" | "final candidate",
): void {
  if (!handles.some((handle) => handle.reference === expectedReference)) {
    throw new Error(
      `Microsandbox archive load did not apply the requested ${role} reference.`,
    );
  }
}

function assertNoCatalogPinReturnedByLoad(
  handles: readonly MicrosandboxImageImportHandle[],
  catalogPin: string,
): void {
  if (
    handles.some((handle) =>
      handle.reference === catalogPin ||
      samePinnedRepositoryDigest(handle.reference, catalogPin)
    )
  ) {
    throw new Error(
      "Microsandbox archive load returned the active catalogue pin; the candidate import is refused.",
    );
  }
}

function assertDistinctFromCatalogPin(
  reference: string,
  catalogPin: string,
  label: string,
): void {
  if (reference === catalogPin) {
    throw new Error(
      `First-party candidate ${label} must not equal the active catalogue pin.`,
    );
  }
}

function assertLiteralNotRunCompliance(
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
): void {
  if (
    receipt.artifactCompliance.runtimeQualification !== "not-run" ||
    receipt.artifactCompliance.eligibleForPromotion !== false
  ) {
    throw new TypeError(
      "Candidate import requires runtimeQualification=not-run and eligibleForPromotion=false.",
    );
  }
}

function assertHostArchitecture(hostArchitecture: string): void {
  if (hostArchitecture !== "arm64") {
    throw new Error(
      "First-party Microsandbox candidate import is reviewed only for native linux/arm64.",
    );
  }
}

function assertSha256(value: string, label: string): void {
  if (!SHA256.test(value)) {
    throw new TypeError(`${label} must be an exact lowercase sha256 digest.`);
  }
}

function assertStagingToken(value: string): void {
  if (!STAGING_TOKEN.test(value)) {
    throw new TypeError(
      "First-party candidate staging token must be a server-generated lowercase nonce.",
    );
  }
}

function stagingLocatorPrefix(
  receipt: FirstPartyMicrosandboxImageCandidateReceipt,
): string {
  return receipt.candidate.locatorTag.slice(
    0,
    MAXIMUM_STAGING_LOCATOR_PREFIX_LENGTH,
  );
}

function createFirstPartyMicrosandboxImageCandidateStagingToken(): string {
  return crypto.randomUUID();
}

function jsonObject(value: unknown, label: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`${label} must be a JSON object.`);
  }
  return value as Record<string, unknown>;
}

function stringArraysEqual(
  left: readonly string[] | null,
  right: readonly string[],
): boolean {
  return left !== null && left.length === right.length &&
    left.every((value, index) => value === right[index]);
}

async function inspectOciIndex(reference: string): Promise<string> {
  if (!reference.includes("@sha256:") || reference.endsWith(":latest")) {
    throw new TypeError(
      "OCI index inspect requires an exact digest-pinned reference.",
    );
  }
  const output = await docker([
    "buildx",
    "imagetools",
    "inspect",
    "--raw",
    reference,
  ]);
  if (!output.success) {
    throw new Error(
      `docker buildx imagetools inspect failed: ${decode(output.stderr).slice(-2_000)}`,
    );
  }
  return decode(output.stdout);
}

async function inspectDockerImage(reference: string): Promise<unknown | undefined> {
  const output = await docker([
    "image",
    "inspect",
    "--format",
    "{{json .}}",
    reference,
  ]);
  if (!output.success) return undefined;
  return JSON.parse(decode(output.stdout)) as unknown;
}

async function pullByDigest(reference: string): Promise<void> {
  if (!reference.includes("@sha256:") || reference.endsWith(":latest")) {
    throw new TypeError(
      "First-party candidate pull requires an exact digest-pinned reference.",
    );
  }
  const output = await docker(["pull", reference]);
  if (!output.success) {
    throw new Error(`docker pull failed: ${decode(output.stderr).slice(-2_000)}`);
  }
}

async function saveDockerImage(reference: string, archivePath: string): Promise<void> {
  const output = await docker(["image", "save", "-o", archivePath, reference]);
  if (!output.success) {
    throw new Error(
      `docker image save failed: ${decode(output.stderr).slice(-2_000)}`,
    );
  }
}

async function createAllowedCandidateArchive(): Promise<
  FirstPartyMicrosandboxTemporaryArchive
> {
  const directory = assertAllowedFirstPartyBootstrapTempPath(
    await Deno.makeTempDir({
      dir: "/tmp",
      prefix: "casys-first-party-microsandbox-candidate-",
    }),
  );
  return Object.freeze({
    directory,
    archivePath: `${directory}/image.tar`,
    cleanup: () => Deno.remove(directory, { recursive: true }),
  });
}

async function docker(args: readonly string[]): Promise<Deno.CommandOutput> {
  return await new Deno.Command("docker", {
    args: [...args],
    stdin: "null",
    stdout: "piped",
    stderr: "piped",
  }).output();
}

function decode(bytes: Uint8Array): string {
  return new TextDecoder().decode(bytes);
}
