import type {
  ThreadFreshness,
  ThreadGraphEdge,
  ThreadGraphEdgeAttestation,
  ThreadGraphNode,
  ThreadGraphRef,
  ThreadRef,
} from "../../presentation/workbench/thread/graph.ts";
import { unavailableEngineeringCaseCatalog } from "../../presentation/workbench/thread/evidence.ts";
import type { ThreadWorkbenchSnapshot } from "../../presentation/workbench/thread/snapshot.ts";

/** Explicit product-design fixture; never presented as live engineering proof. */
export const GENERIC_THREAD_FIXTURE: ThreadWorkbenchSnapshot = {
  schemaVersion: "thread-workbench/0.2",
  id: "thread-generic-chg-184",
  subject: {
    id: "GEN-01",
    label: "Reference Generic Product",
    program: "generic demonstration fixture",
  },
  generatedAt: "2026-08-01T08:42:16.000Z",
  source: "fixture",
  sourceLabel: "LABELLED PRODUCT FIXTURE — NOT LIVE EVIDENCE",
  change: {
    id: "CHG-184",
    title: "Reduce support bracket wall thickness",
    summary:
      "The brew-unit support bracket changed from 2.2 mm to 1.8 mm to reduce material use.",
    author: "Casys engineering agent",
    revision: "cad/bracket@7f3a9c2",
    changedAt: "2026-08-01T08:31:02.000Z",
    status: "partially_evaluated",
    files: ["bracket.py", "GEN-01.sysml"],
  },
  engineeringCases: unavailableEngineeringCaseCatalog(),
  graph: {
    nodes: [
      graphNode(
        { kind: "change", id: "CHG-184" },
        "Reduce support bracket wall thickness",
        "Git",
        "fresh",
        "2.2 mm → 1.8 mm",
        { kind: "change", id: "CHG-184" },
      ),
      graphNode(
        { kind: "artifact", id: "ART-SYSML-018" },
        "GEN-01 requirement baseline",
        "SysON",
        "fresh",
        "model/GEN-01@18",
        { kind: "artifact", id: "ART-SYSML-018" },
        "SysML v2 model",
      ),
      graphNode(
        { kind: "artifact", id: "ART-CAD-018" },
        "Brew-unit support bracket",
        "build123d",
        "fresh",
        "cad/bracket@18",
        { kind: "artifact", id: "ART-CAD-018" },
        "Parametric CAD model",
      ),
      graphNode(
        { kind: "artifact", id: "ART-STEP-018" },
        "Bracket manufacturing geometry",
        "build123d",
        "fresh",
        "step/bracket@18",
        { kind: "artifact", id: "ART-STEP-018" },
        "STEP AP242",
      ),
      graphNode(
        { kind: "artifact", id: "ART-FEA-018" },
        "Support bracket static solve",
        "CalculiX",
        "fresh",
        "fea/bracket@18",
        { kind: "artifact", id: "ART-FEA-018" },
        "CalculiX result bundle",
      ),
      graphNode(
        { kind: "artifact", id: "ART-THERMAL-017" },
        "Enclosure thermal scenario",
        "Modelica",
        "stale",
        "thermal/enclosure@17",
        { kind: "artifact", id: "ART-THERMAL-017" },
        "Modelica result",
      ),
      graphNode(
        { kind: "observation", id: "OBS-MASS" },
        "Bracket mass",
        "build123d",
        "fresh",
        "417 g",
        { kind: "observation", id: "OBS-MASS" },
      ),
      graphNode(
        { kind: "observation", id: "OBS-STRESS-MAX" },
        "Maximum von Mises stress",
        "CalculiX",
        "fresh",
        "132 MPa",
        { kind: "observation", id: "OBS-STRESS-MAX" },
      ),
      graphNode(
        { kind: "observation", id: "OBS-CLEARANCE" },
        "Brew group service clearance",
        "build123d",
        "fresh",
        "2.6 mm",
        { kind: "observation", id: "OBS-CLEARANCE" },
      ),
      graphNode(
        { kind: "observation", id: "OBS-TEMP-SHELL" },
        "Maximum enclosure temperature",
        "Modelica",
        "stale",
        "53.7 °C",
        { kind: "observation", id: "OBS-TEMP-SHELL" },
      ),
      graphNode(
        { kind: "requirement", id: "REQ-MECH-014" },
        "Illustrative bracket stress",
        "SysON",
        "failed",
        "max(von_mises) ≤ 120 MPa",
        { kind: "requirement", id: "REQ-MECH-014" },
      ),
      graphNode(
        { kind: "requirement", id: "REQ-MASS-006" },
        "Bracket mass budget",
        "SysON",
        "fresh",
        "mass ≤ 450 g",
        { kind: "requirement", id: "REQ-MASS-006" },
      ),
      graphNode(
        { kind: "requirement", id: "REQ-SVC-009" },
        "Service tool clearance",
        "SysON",
        "fresh",
        "clearance ≥ 2.0 mm",
        { kind: "requirement", id: "REQ-SVC-009" },
      ),
      graphNode(
        { kind: "requirement", id: "REQ-THERM-021" },
        "Touchable enclosure temperature",
        "SysON",
        "stale",
        "max(shell_temperature) ≤ 60 °C",
        { kind: "requirement", id: "REQ-THERM-021" },
      ),
      graphNode(
        { kind: "violation", id: "VIO-MECH-014" },
        "Illustrative stress limit exceeded",
        "SysON",
        "failed",
        "blocking · open",
        { kind: "violation", id: "VIO-MECH-014" },
      ),
      graphNode(
        { kind: "action", id: "ACT-RIB" },
        "Increase upper rib to 4.5 mm",
        "build123d",
        "fresh",
        "change · ready",
        { kind: "artifact", id: "ART-CAD-018" },
      ),
      graphNode(
        { kind: "action", id: "ACT-THICKNESS" },
        "Restore wall thickness to 2.0 mm",
        "build123d",
        "fresh",
        "change · ready",
        { kind: "artifact", id: "ART-CAD-018" },
      ),
      graphNode(
        { kind: "action", id: "ACT-INSPECT" },
        "Inspect stress concentration",
        "CalculiX",
        "fresh",
        "inspect · ready",
        { kind: "observation", id: "OBS-STRESS-MAX" },
      ),
      graphNode(
        { kind: "action", id: "ACT-THERMAL" },
        "Recompute thermal scenario",
        "Modelica",
        "fresh",
        "recompute · ready",
        { kind: "artifact", id: "ART-THERMAL-017" },
      ),
      {
        ...graphNode(
          { kind: "change", id: "CHG-DRIPTRAY-030" },
          "Correction DripTray 28 → 30 mm",
          "digital-thread",
          "fresh",
          "DripTray width 28 mm → 30 mm",
          { kind: "change", id: "CHG-DRIPTRAY-030" },
        ),
        recordedAt: "2026-08-01T09:03:00.000Z",
      },
      {
        ...graphNode(
          { kind: "artifact", id: "ART-DRIPTRAY-FEA-028" },
          "DripTray mechanical proof",
          "CalculiX",
          "stale",
          "drip-tray/static@28 · historical",
          { kind: "artifact", id: "ART-DRIPTRAY-FEA-028" },
          "solver-result",
        ),
        recordedAt: "2026-08-01T08:47:00.000Z",
      },
      {
        ...graphNode(
          { kind: "artifact", id: "ART-DRIPTRAY-FEA-030" },
          "DripTray mechanical proof",
          "CalculiX",
          "fresh",
          "drip-tray/static@30 · recalculated",
          { kind: "artifact", id: "ART-DRIPTRAY-FEA-030" },
          "solver-result",
        ),
        recordedAt: "2026-08-01T09:03:42.000Z",
      },
      {
        ...graphNode(
          { kind: "artifact", id: "ART-THERMAL-NOMINAL-018" },
          "Nominal thermal scenario",
          "Modelica",
          "fresh",
          "thermal/nominal@18 · current",
          { kind: "artifact", id: "ART-THERMAL-NOMINAL-018" },
          "solver-result",
        ),
        recordedAt: "2026-08-01T08:58:00.000Z",
      },
      {
        ...graphNode(
          { kind: "artifact", id: "ART-BOM-GEN01-018" },
          "GEN-01 manufacturing BOM",
          "ERPNext",
          "fresh",
          "BOM-GEN01@18 · current",
          { kind: "artifact", id: "ART-BOM-GEN01-018" },
          "bom",
        ),
        recordedAt: "2026-08-01T08:57:00.000Z",
      },
    ],
    edges: [
      structureEdge(
        "fixture:input:sysml:cad",
        { kind: "artifact", id: "ART-SYSML-018" },
        { kind: "artifact", id: "ART-CAD-018" },
        "input_to",
        "The fixture explicitly lists the SysML baseline as a CAD input.",
      ),
      structureEdge(
        "fixture:input:cad:step",
        { kind: "artifact", id: "ART-CAD-018" },
        { kind: "artifact", id: "ART-STEP-018" },
        "input_to",
        "The fixture explicitly lists the CAD model as a STEP input.",
      ),
      structureEdge(
        "fixture:input:step:fea",
        { kind: "artifact", id: "ART-STEP-018" },
        { kind: "artifact", id: "ART-FEA-018" },
        "input_to",
        "The fixture explicitly lists the STEP geometry as a CalculiX input.",
        {
          consumptionId: "fixture-consumption-step-fea",
          status: "verified",
          producerFingerprint: "sha256:03d3ab02f66c97d0",
          consumedFingerprint: "sha256:03d3ab02f66c97d0",
          checkedAt: "2026-08-01T08:38:52.000Z",
        },
      ),
      structureEdge(
        "fixture:input:cad:thermal",
        { kind: "artifact", id: "ART-CAD-018" },
        { kind: "artifact", id: "ART-THERMAL-017" },
        "input_to",
        "The fixture explicitly lists the CAD model as a Modelica input.",
        {
          consumptionId: "fixture-consumption-cad-thermal",
          status: "mismatch",
          producerFingerprint: "sha256:cc3e171fa21bf507",
          consumedFingerprint: "sha256:6ecf1199c31aa098",
          checkedAt: "2026-08-01T08:42:16.000Z",
        },
      ),
      structureEdge(
        "fixture:source:cad:mass",
        { kind: "artifact", id: "ART-CAD-018" },
        { kind: "observation", id: "OBS-MASS" },
        "source_of",
        "The fixture explicitly identifies the CAD artifact as the mass source.",
      ),
      structureEdge(
        "fixture:source:fea:stress",
        { kind: "artifact", id: "ART-FEA-018" },
        { kind: "observation", id: "OBS-STRESS-MAX" },
        "source_of",
        "The fixture explicitly identifies the FEA artifact as the stress source.",
      ),
      structureEdge(
        "fixture:source:cad:clearance",
        { kind: "artifact", id: "ART-CAD-018" },
        { kind: "observation", id: "OBS-CLEARANCE" },
        "source_of",
        "The fixture explicitly identifies the CAD artifact as the clearance source.",
      ),
      structureEdge(
        "fixture:source:thermal:temperature",
        { kind: "artifact", id: "ART-THERMAL-017" },
        { kind: "observation", id: "OBS-TEMP-SHELL" },
        "source_of",
        "The fixture explicitly identifies the Modelica artifact as the temperature source.",
      ),
      provenanceEdge(
        "fixture:changes:driptray-030",
        { kind: "change", id: "CHG-DRIPTRAY-030" },
        { kind: "artifact", id: "ART-DRIPTRAY-FEA-030" },
        "changes",
        "The recorded DripTray dimension correction requires this replacement proof.",
      ),
      provenanceEdge(
        "fixture:supersedes:driptray-fea-030",
        { kind: "artifact", id: "ART-DRIPTRAY-FEA-028" },
        { kind: "artifact", id: "ART-DRIPTRAY-FEA-030" },
        "supersedes",
        "The 30 mm DripTray solve replaces the retained 28 mm evidence record.",
      ),
    ],
  },
  // The fixture is deliberately not a substitute family projector. The live
  // backend owns this quotient; an empty, explicitly typed projection keeps
  // the fallback labelled and exercises the neutral compact state.
  evidenceFamilyGraph: {
    schemaVersion: "thread-evidence-family-graph/1.0",
    asOf: {
      snapshotId: "thread-generic-chg-184",
      revision: 1,
    },
    families: [],
    edges: [],
    omittedSelfLoops: [],
    omittedCycleEdges: [],
  },
  flow: [
    {
      id: "flow-change",
      label: "Change",
      system: "Git",
      freshness: "fresh",
      summary: "1.8 mm wall",
      selection: { kind: "change", id: "CHG-184" },
      dependsOn: [],
    },
    {
      id: "flow-system",
      label: "System model",
      system: "SysON",
      freshness: "fresh",
      summary: "4 traced requirements",
      selection: { kind: "artifact", id: "ART-SYSML-018" },
      dependsOn: [],
    },
    {
      id: "flow-cad",
      label: "Geometry",
      system: "build123d",
      freshness: "fresh",
      summary: "STEP r18",
      selection: { kind: "artifact", id: "ART-STEP-018" },
      dependsOn: [],
    },
    {
      id: "flow-fea",
      label: "Structural proof",
      system: "CalculiX",
      freshness: "fresh",
      summary: "132 MPa peak",
      selection: { kind: "observation", id: "OBS-STRESS-MAX" },
      dependsOn: [],
    },
    {
      id: "flow-thermal",
      label: "Thermal proof",
      system: "Modelica",
      freshness: "stale",
      summary: "invalidated by r18",
      selection: { kind: "observation", id: "OBS-TEMP-SHELL" },
      dependsOn: [],
    },
    {
      id: "flow-verdict",
      label: "Verdict",
      system: "SysON",
      freshness: "failed",
      summary: "1 named violation",
      selection: { kind: "violation", id: "VIO-MECH-014" },
      dependsOn: [],
    },
  ],
  artifacts: [
    {
      id: "ART-SYSML-018",
      label: "GEN-01 requirement baseline",
      kind: "SysML v2 model",
      system: "SysON",
      revision: "model/GEN-01@18",
      freshness: "fresh",
      fingerprint: "sha256:8f4ab1be02c7c96d",
      uri: "syson://projects/generic/revisions/18",
      producedAt: "2026-08-01T08:31:08.000Z",
      dependsOn: [],
    },
    {
      id: "ART-CAD-018",
      label: "Brew-unit support bracket",
      kind: "Parametric CAD model",
      system: "build123d",
      revision: "cad/bracket@18",
      freshness: "fresh",
      fingerprint: "sha256:cc3e171fa21bf507",
      uri: "artifact://generic/cad/bracket/r18/model",
      producedAt: "2026-08-01T08:33:42.000Z",
      producedBy: "build123d_export",
      dependsOn: ["ART-SYSML-018"],
    },
    {
      id: "ART-STEP-018",
      label: "Bracket manufacturing geometry",
      kind: "STEP AP242",
      system: "build123d",
      revision: "step/bracket@18",
      freshness: "fresh",
      fingerprint: "sha256:03d3ab02f66c97d0",
      uri: "artifact://generic/cad/bracket/r18/bracket.step",
      producedAt: "2026-08-01T08:33:43.000Z",
      producedBy: "build123d_export",
      dependsOn: ["ART-CAD-018"],
    },
    {
      id: "ART-FEA-018",
      label: "Support bracket static solve",
      kind: "CalculiX result bundle",
      system: "CalculiX",
      revision: "fea/bracket@18",
      freshness: "fresh",
      fingerprint: "sha256:fd61cf0511287d34",
      uri: "artifact://generic/fea/bracket/r18/results.frd",
      producedAt: "2026-08-01T08:38:51.000Z",
      producedBy: "calculix_solve_static",
      dependsOn: ["ART-STEP-018"],
      attestation: {
        status: "verified",
        sourceArtifactId: "ART-STEP-018",
        producerFingerprint: "sha256:03d3ab02f66c97d0",
        consumedFingerprint: "sha256:03d3ab02f66c97d0",
        checkedAt: "2026-08-01T08:38:52.000Z",
      },
    },
    {
      id: "ART-THERMAL-017",
      label: "Enclosure thermal scenario",
      kind: "Modelica result",
      system: "Modelica",
      revision: "thermal/enclosure@17",
      freshness: "stale",
      fingerprint: "sha256:0d92c6ae13e8472f",
      uri: "artifact://generic/thermal/enclosure/r17/result.mat",
      producedAt: "2026-07-31T19:16:04.000Z",
      producedBy: "modelica_simulate",
      dependsOn: ["ART-CAD-018"],
      attestation: {
        status: "mismatch",
        sourceArtifactId: "ART-CAD-018",
        producerFingerprint: "sha256:cc3e171fa21bf507",
        consumedFingerprint: "sha256:6ecf1199c31aa098",
        checkedAt: "2026-08-01T08:42:16.000Z",
      },
    },
    {
      id: "ART-DRIPTRAY-FEA-028",
      label: "DripTray mechanical proof",
      kind: "CalculiX result bundle",
      system: "CalculiX",
      revision: "drip-tray/static@28",
      freshness: "stale",
      fingerprint: "sha256:driptray28historical",
      uri: "artifact://generic/drip-tray/r28/results.frd",
      producedAt: "2026-08-01T08:47:00.000Z",
      producedBy: "calculix_solve_static",
      dependsOn: [],
    },
    {
      id: "ART-DRIPTRAY-FEA-030",
      label: "DripTray mechanical proof",
      kind: "CalculiX result bundle",
      system: "CalculiX",
      revision: "drip-tray/static@30",
      freshness: "fresh",
      fingerprint: "sha256:driptray30recalculated",
      uri: "artifact://generic/drip-tray/r30/results.frd",
      producedAt: "2026-08-01T09:03:42.000Z",
      producedBy: "calculix_solve_static",
      dependsOn: [],
    },
    {
      id: "ART-THERMAL-NOMINAL-018",
      label: "Nominal thermal scenario",
      kind: "Modelica result",
      system: "Modelica",
      revision: "thermal/nominal@18",
      freshness: "fresh",
      fingerprint: "sha256:thermalnominal18",
      uri: "artifact://generic/thermal/nominal/r18/result.mat",
      producedAt: "2026-08-01T08:58:00.000Z",
      producedBy: "modelica_simulate",
      dependsOn: [],
    },
    {
      id: "ART-BOM-GEN01-018",
      label: "GEN-01 manufacturing BOM",
      kind: "ERPNext BOM",
      system: "ERPNext",
      revision: "BOM-GEN01@18",
      freshness: "fresh",
      fingerprint: "sha256:bomgeneric18",
      uri: "erpnext://BOM-GEN01-018",
      producedAt: "2026-08-01T08:57:00.000Z",
      producedBy: "erpnext_bom_get",
      dependsOn: [],
    },
  ],
  observations: [
    {
      id: "OBS-MASS",
      label: "Bracket mass",
      value: 0.417,
      unit: "kg",
      display: "417 g",
      sourceArtifactId: "ART-CAD-018",
      requirementIds: ["REQ-MASS-006"],
      freshness: "fresh",
      measuredAt: "2026-08-01T08:33:43.000Z",
    },
    {
      id: "OBS-STRESS-MAX",
      label: "Maximum von Mises stress",
      value: 132,
      unit: "MPa",
      display: "132 MPa",
      sourceArtifactId: "ART-FEA-018",
      requirementIds: ["REQ-MECH-014"],
      freshness: "fresh",
      measuredAt: "2026-08-01T08:38:51.000Z",
    },
    {
      id: "OBS-CLEARANCE",
      label: "Brew group service clearance",
      value: 2.6,
      unit: "mm",
      display: "2.6 mm",
      sourceArtifactId: "ART-CAD-018",
      requirementIds: ["REQ-SVC-009"],
      freshness: "fresh",
      measuredAt: "2026-08-01T08:33:43.000Z",
    },
    {
      id: "OBS-TEMP-SHELL",
      label: "Maximum enclosure temperature",
      value: 53.7,
      unit: "°C",
      display: "53.7 °C",
      sourceArtifactId: "ART-THERMAL-017",
      requirementIds: ["REQ-THERM-021"],
      freshness: "stale",
      measuredAt: "2026-07-31T19:16:04.000Z",
    },
  ],
  requirements: [
    {
      id: "REQ-MECH-014",
      label: "Illustrative bracket stress",
      source: "Synthetic fixture · not present in live SysON",
      sourceElementId: "fixture:REQ-MECH-014",
      expression: "max(von_mises) ≤ 120 MPa",
      status: "fail",
      observationIds: ["OBS-STRESS-MAX"],
      violationIds: ["VIO-MECH-014"],
      rationale:
        "Synthetic UI scenario only; 120 MPa is not an approved GenericAssembly design limit.",
    },
    {
      id: "REQ-MASS-006",
      label: "Bracket mass budget",
      source: "SysON · GEN-01 mass allocation",
      sourceElementId: "fixture:REQ-MASS-006",
      expression: "mass ≤ 450 g",
      status: "pass",
      observationIds: ["OBS-MASS"],
      violationIds: [],
      rationale: "The bracket remains 33 g below its allocation.",
    },
    {
      id: "REQ-SVC-009",
      label: "Service tool clearance",
      source: "SysON · GEN-01 serviceability",
      sourceElementId: "fixture:REQ-SVC-009",
      expression: "clearance ≥ 2.0 mm",
      status: "pass",
      observationIds: ["OBS-CLEARANCE"],
      violationIds: [],
      rationale: "The current geometry preserves 0.6 mm of clearance margin.",
    },
    {
      id: "REQ-THERM-021",
      label: "Touchable enclosure temperature",
      source: "SysON · GEN-01 thermal safety",
      sourceElementId: "fixture:REQ-THERM-021",
      expression: "max(shell_temperature) ≤ 60 °C",
      status: "unresolved",
      observationIds: ["OBS-TEMP-SHELL"],
      violationIds: [],
      rationale: "The latest thermal evidence predates geometry revision 18.",
    },
  ],
  violations: [
    {
      id: "VIO-MECH-014",
      name: "Illustrative stress limit exceeded",
      severity: "blocking",
      status: "open",
      requirementId: "REQ-MECH-014",
      observationId: "OBS-STRESS-MAX",
      message:
        "Fixture geometry produces 132 MPa against a synthetic 120 MPa UI limit. This is not a live product verdict.",
      margin: "−12 MPa · −10.0%",
      evidence: ["ART-STEP-018", "ART-FEA-018"],
      proposedActionIds: ["ACT-RIB", "ACT-THICKNESS", "ACT-INSPECT"],
    },
  ],
  actions: [
    {
      id: "ACT-RIB",
      label: "Increase upper rib to 4.5 mm",
      description:
        "Prepare a bounded CAD parameter change, then invalidate structural evidence.",
      kind: "change",
      targetId: "ART-CAD-018",
      system: "build123d",
      readiness: "ready",
      requiresConfirmation: true,
    },
    {
      id: "ACT-THICKNESS",
      label: "Restore wall thickness to 2.0 mm",
      description: "Prepare the smallest thickness correction suggested by the agent.",
      kind: "change",
      targetId: "ART-CAD-018",
      system: "build123d",
      readiness: "ready",
      requiresConfirmation: true,
    },
    {
      id: "ACT-INSPECT",
      label: "Inspect stress concentration",
      description:
        "Open the failing region and its source mesh without recomputing it.",
      kind: "inspect",
      targetId: "OBS-STRESS-MAX",
      system: "CalculiX",
      readiness: "ready",
      requiresConfirmation: false,
    },
    {
      id: "ACT-THERMAL",
      label: "Recompute thermal scenario",
      description: "Prepare a Modelica run against geometry revision 18.",
      kind: "recompute",
      targetId: "ART-THERMAL-017",
      system: "Modelica",
      readiness: "ready",
      requiresConfirmation: true,
    },
  ],
};

function graphNode(
  ref: ThreadGraphRef,
  label: string,
  system: string,
  freshness: ThreadFreshness,
  summary: string,
  selection?: ThreadRef,
  artifactKind?: string,
): ThreadGraphNode {
  return {
    id: `graph:${ref.kind}:${ref.id}`,
    ref,
    entityKind: ref.kind,
    ...(artifactKind ? { artifactKind } : {}),
    label,
    system,
    freshness,
    summary,
    ...(selection ? { selection } : {}),
  };
}

function structureEdge(
  id: string,
  from: ThreadGraphRef,
  to: ThreadGraphRef,
  relation: "input_to" | "source_of",
  rationale: string,
  attestation?: ThreadGraphEdgeAttestation,
): ThreadGraphEdge {
  return {
    id,
    from,
    to,
    relation,
    rationale,
    origin: "structure",
    ...(attestation ? { attestation } : {}),
  };
}

function provenanceEdge(
  id: string,
  from: ThreadGraphRef,
  to: ThreadGraphRef,
  relation: "changes" | "supersedes",
  rationale: string,
): ThreadGraphEdge {
  return {
    id,
    from,
    to,
    relation,
    rationale,
    origin: "provenance",
  };
}
